eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates: 
          - Path=/api/product
     
        - id: order-service
          uri: lb://order-service
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
